export enum Label {
  WORK_ZONE_TITLE = "Zona de entrega",
  MENU_TITLE = "Menu",
  SHOP_NAME = "PIZZERIA ALDO",
  WORK_TIME_TITLE = "🕔 Horarios",
  WORK_TIME = "Martes a Domingos de 19:00 a 23:00hs",
  DIGITAL_MENU_LABEL = "📱 Ingresa al menu digital! ",
  REGARDS_LABEL = "😊 ¡Gracias por elegirnos!",
  COMPLETE_FORM_LABEL = "Complete el pedido:",
  DELIVERY_lABEL = "Enviar pedido por Whatsapp",
  PRE_DELIVERY_lABEL = "Realizar pedido",
  TAKEIT_lABEL = "Chat whatsapp lo retiro",
  AUTHOR = "Aldo 2024",
  MESSAGE_DELIVERY = "https://api.whatsapp.com/send?phone=5491150464875&text=Pedido%20pizza%20delivery:%20",
}
